### ISSUE TITLE
async pipe with loading behavior

### ISSUE THREAD

**Issue by JaimeStill** [nclarx/component-vs-async-pipe-subscriptions-angular#1]
Not an issue, but I saw you generated this repo and I wanted to share a pattern that's been infinitely helpful for me working with Angular.

You can use the `async` pipe to establish a variable, and reference an `<ng-template>` while that variable is null (demonstrating that the value is still being fetched). The basic pattern is as follows:

```html
<ng-template #loading>
    <!-- whatever you want to show while loading -->
</ng-template>
<ng-container *ngIf="service.stream$ | async as stream else loading">
    <!-- render when the stream has resolved with a value (even if it's an empty array) -->
</ng-container>
```

You can see an example of this on [this StackBlitz](https://stackblitz.com/edit/docs-rxjs?file=src%2Fapp%2Froutes%2Foperators%2Fchildren%2Fshow-search.component.html) with the route found [here](https://docs-rxjs.stackblitz.io/operators/show-search). For full details on how this route works, I have a write up in [this readme](https://github.com/JaimeStill/PatternsAndPractices/blob/master/a1-rxjs.md#show-search).

**Comment by nclarx** [comment]
That's an excellent pattern - so much neater than adding a second `*ngIf`. Thanks for sharing.

I was moving this off Stackblitz into this repo because I wanted to keep a bunch of my answers to things on StackOverflow.

**Comment by JaimeStill** [comment]
No worries, always glad to share knowledge!
